apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: vote
spec:
  type: ExternalName
  externalName: redis.redis.svc.cluster.local
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
